### PR TITLE
Bug 2060007: Makefile fixes for: no rule 'docker-push'

### PR DESCRIPTION
**Pull request by ukalifon**
Remove calls to target docker-push, which doesn't exist

### CODE REVIEW

**Comment by pacevedom** [comment]
Not sure, but are we allowed to push to 4.10 without a BZ?

**Comment by qbarrand** [comment]
Yes, I would first merge this into `master`, then cherry-picked into the release branch if possible.
Also, could we merge this change upstream first?

**Comment by ukalifon** [comment]
@qbarrand @yevgeny-shnaidman It doesn't make sense to merge this into master first, because the Makefile there is vastly different from this one, and in master the container command is parameterized. So instead, I fixed my PR to have the container command parameterized in this branch as well, pretty similar to how it is in master.

**Comment by ukalifon** [comment]
BZ is here: https://bugzilla.redhat.com/show_bug.cgi?id=2060007

**Comment by qbarrand** [comment]
@ukalifon please prepend the PR's title with `Bug 2060007:` and then comment `/bugzilla refresh`.

/lgtm

**Pull request merged**
