### PR TITLE
Bring recent changes from upstream

### PR DESCRIPTION
**Pull request by qbarrand**
This PR brings a number of commits from upstream, with conflicts resolved where required.

### CODE REVIEW

**Comment by qbarrand** [comment]
Hold because of code freeze.
/hold

**Comment by bthurber** [comment]
@qbarrand This will need work before being able to merge.  SInce we are at code freeze today for 4.10 we need to discuss options for targeting a z-stream release.

**Comment by qbarrand** [comment]
@pacevedom PTAL

**Comment by qbarrand** [comment]
@bthurber do we want to include this PR into 4.10 at all? That's quite a lot of changes for a z-stream release, even though they are mostly about testing and refactoring.

**Pull request merged**
