### PR TITLE
Disabling as CVO operator

### PR DESCRIPTION
**Pull request by jupierce**
Inclusion in the CVO requires architecture team agreement.

### CODE REVIEW

**Comment by jupierce** [comment]
https://coreos.slack.com/archives/C01CQA76KMX/p1607365944195700?thread_ts=1607102032.127200&cid=C01CQA76KMX

**Review by wking — APPROVED** [review]

**Comment by ArangoGutierrez** [comment]
@jupierce I believe that if we rebase this branch patch into current master test will pass easier. the lasts merged PR solves some flaky issues being present in tests in this current PR

**Comment by jupierce** [comment]
Rebased

**Pull request merged**
