### PR TITLE
Add only yaml files to the bundle

### PR DESCRIPTION
**Pull request by SchSeba**
Signed-off-by: Sebastian Sch <sebassch@gmail.com>

### CODE REVIEW

**Review by bthurber — APPROVED** [review]
/approve

**Comment by qbarrand** [comment]
/hold
I am not sure what problem this issue solves.

**Comment by ybettan** [comment]
We are doing the same in DTK https://github.com/openshift/driver-toolkit/blob/1c9890fc6f348f605b589fadfda8a9f3eb9f7f57/Dockerfile#L54 and ART is able to parse it correctly.

**Comment by SchSeba** [comment]
@ybettan the difference is that the DTK is not installed via OLM.

Or it miss something?

This is the comment from the OLM team about bundles that contains image streams:

```
I see the extra Kind: ImageStream that is failing with status:  UnsupportedResource
```

if you check the files in the bundle folder the only file that contains imageStream is the image-reference one which is not even used by the operator.

**Comment by mgourin** [comment]
@qbarrand @SchSeba @yevgeny-shnaidman 
Is there any issue with merging this?

**Comment by qbarrand** [comment]
@mgourin @SchSeba I just ran:
```
make local-image-build manifests bundle bundle-build IMG=quay.io/quba/sro:latest BUNDLE_IMG=quay.io/quba/sro-bundle:latest
podman push quay.io/quba/sro:latest
podman push quay.io/quba/sro-bundle:latest
operator-sdk --verbose run bundle quay.io/quba/sro-bundle:latest
```
And did not encounter any issue. To me that means that the generated bundle is correct?

**Comment by mgourin** [comment]
> @mgourin @SchSeba I just ran:
> 
> ```
> make local-image-build manifests bundle bundle-build IMG=quay.io/quba/sro:latest BUNDLE_IMG=quay.io/quba/sro-bundle:latest
> podman push quay.io/quba/sro:latest
> podman push quay.io/quba/sro-bundle:latest
> operator-sdk --verbose run bundle quay.io/quba/sro-bundle:latest
> ```
> 
> And did not encounter any issue. To me that means that the generated bundle is correct?

IIRC this commit was made in order to avoid an issue when installing the SRO, wherein the csv is stuck on pending due to the InstallPlan not supporting an ImageStream definition which was somehow entered into the build.

This problem was documented here:
https://issues.redhat.com/browse/OCPBUGS-1591

@SchSeba could you provide any additional info here or in the commit description?

**Comment by SchSeba** [comment]
closing this one we implement a w/a as part of our CI build index

https://github.com/openshift-kni/cnf-features-deploy/pull/1327

**Pull request closed without merging**
