### PR TITLE
Bug 2093357: hub and spokes: add OCP version retrieval and fix ICE driver

### PR DESCRIPTION
**Pull request by pacevedom**
Add functionality to extract OCP version from images and use it as
a helm variable.
Tweak ICE driver example to fix bug 2093357

### CODE REVIEW

**Comment by cdvultur** [comment]
This fixes the driver problem. Still wondering if , with the new kernel ( in case of the reboot while OCP upgrades ) the old driver can be loaded or not and what happens in that case. 

If it does not load ( error our the service execution ) , will it do the same thing ?

**Comment by pacevedom** [comment]
> This fixes the driver problem. Still wondering if , with the new kernel ( in case of the reboot while OCP upgrades ) the old driver can be loaded or not and what happens in that case.
> 
> If it does not load ( error our the service execution ) , will it do the same thing ?

This is a special situation that should be handled with care. If you know you are going to run into incompatibilities (I need X version of the kernel because some symbols are only there, for example) you would need to plan in advance. This means you would need to build the driver container before the actual upgrade.

What I wonder is when the `openshiftVersion` from the spoke to the hub is upgraded. If this happens before the machine config template is applied (which I doubt), then you dont have any issues.

**Comment by cdvultur** [comment]
From what I see, the openshiftVersion is updated at the end of the upgrade. 

If you start upgrade, and run `oc get clusterversion` you will see the old version of the cluster in the VERSION column and the fact that the cluster is upgraded in the STATUS column. Once it reaches 100% , the VERSION is bumped UP .

**Pull request merged**
