### PR TITLE
Syncing Upstream to Downstream CVO enablement

### PR DESCRIPTION
**Pull request by zvonkok**
This PR labels the Dockefile for CVO inclusion.
Adds auto-generation of CVO manifests and adds image-references and ClusterOperator CR.

### CODE REVIEW

**Comment by zvonkok** [comment]
@dagrayvid @ArangoGutierrez Sync from upstream, all future changes regarding CVO should go here.

**Comment by dagrayvid** [comment]
@zvonkok can we delete the cvo-manifests directory that is still there? (manifests/ is also there)

**Pull request merged**
