### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by qbarrand**
This PR includes the following upstream PRs:
- https://github.com/openshift-psap/special-resource-operator/pull/121
- https://github.com/openshift-psap/special-resource-operator/pull/133
- https://github.com/openshift-psap/special-resource-operator/pull/175

### CODE REVIEW

**Comment by ybettan** [comment]
I don't see any issue with the PR.

Lets just wait for one more review as I wasn't reviewing https://github.com/openshift-psap/special-resource-operator/pull/133.

**Comment by qbarrand** [comment]
Thank you for reviewing. Actually, openshift-psap#133 addresses two bugs, one of which is not included in this repo.
So that PR has been stripped down to just fix [`assets.go`](https://github.com/openshift/special-resource-operator/pull/83/commits/d74da2570a2c75390cf5a21cd711d50746ad028b) and its unit tests.

**Review by pacevedom — APPROVED** [review]

**Pull request merged**
