### PR TITLE
Bug 2059843: add new metrics, completedKind and used Nodes

### PR DESCRIPTION
**Pull request by ybettan**

### CODE REVIEW

**Comment by qbarrand** [comment]
LGTM, but why isn't the `e2e-aws-ocp` running on this PR? Is it because we're not merging into `master`?

**Comment by qbarrand** [comment]
/lgtm
/hold

Please feel free to unhold if we want to merge this although the e2e test did not run.

**Comment by bthurber** [comment]
> /lgtm /hold
> 
> Please feel free to unhold if we want to merge this although the e2e test did not run.

@ybettan thoughts on the tests?

**Comment by ybettan** [comment]
@yevgeny-shnaidman Is the owner of this PR. (this is his commit), I created the PR itself for technical reasons.

**Pull request merged**
