### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by leo8a**

### CODE REVIEW

**Comment by dagrayvid** [comment]
Hello @leo8a, thanks for the PR with some good ideas for improvements! Could you open a similar PR upstream instead:
https://github.com/openshift-psap/special-resource-operator

**Comment by leo8a** [comment]
Hi @dagrayvid, sure np, thanks.

**Comment by kpouget** [comment]
https://github.com/openshift-psap/special-resource-operator/pull/80

**Pull request closed without merging**
